name: "Bondis Río Cuarto"

description: "Mirror de los horarios de transporte público en Río Cuarto en un sitio minimalista pensado para resolver los problemas en el servicio del sitio oficial de SATRC."
author: "ls&bn"

# url: "http://localhost:4000"
 url: "https://bondis-rio-cuarto.github.io/horarios"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
