name: "Bondis Río Cuarto"

description: "Respaldo de información sobre horarios SATCRC - Transporte público de colectivos en la ciudad de Río Cuarto, Córdoba ante problemas en el sitio oficial."
author: "ls&bn"

url: "http://localhost:4000"
#url: "https://bondis-rio-cuarto.github.io/horarios"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
